spring:
  application:
    name: account
  threads:
    virtual:
      enabled: true

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 3
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/serp/protocol/openid-connect/certs
          issuer-uri: http://localhost:8180/realms/serp

app:
  keycloak:
    url: http://localhost:8180
    jwk-set-uri: http://localhost:8180/realms/serp/protocol/openid-connect/certs
    expected-issuer: http://localhost:8180/realms/serp
    expected-audience: serp-account
    realm: serp
    client-id: serp-account
    client-secret: ${CLIENT_SECRET}

    admin:
      username: ${KEYCLOAK_ADMIN_USER}
      password: ${KEYCLOAK_ADMIN_PASSWORD}
      client-id: admin-cli

  security:
    admin:
      email: serp.org@gmail.com
      password: SuperAdmin@123

    filter:
      publicUrls:
        - first: /api/v1/auth/login
          second: POST
        - first: /api/v1/auth/register
          second: POST
        - first: /api/v1/auth/get-token
          second: POST
        - first: /api/v1/auth/refresh-token
          second: POST
        - first: /api/v1/auth/revoke-token
          second: POST
        - first: /api/v1/permissions/**
          second: GET
        - first: /api/v1/roles/**
          second: GET
        - first: /api/v1/modules/**
          second: GET
        - first: /api/v1/menu-displays/**
          second: GET
        - first: /api/v1/keycloak/**
          second: GET
        - first: /api/v1/subscription-plans/**
          second: GET
      protectedUrls:
        # ==================== SERP ADMIN ====================
        - url-pattern: /api/v1/admin/**
          roles:
            - SUPER_ADMIN
            - SYSTEM_MODERATOR
          permissions:

        # =================== ORGANIZATION CONTROLLER ====================
        - url-pattern: /api/v1/organizations/me
          roles:
            - SUPER_ADMIN
            - SYSTEM_MODERATOR
            - ORG_USER
          permissions:

        # ==================== USER CONTROLLER ====================
        - url-pattern: /api/v1/users/profile/me
          roles:
            - SUPER_ADMIN
            - SYSTEM_MODERATOR
            - ORG_USER
          permissions:
        - url-pattern: /api/v1/users
          roles:
            - SUPER_ADMIN
            - SYSTEM_MODERATOR
            - ORG_USER
          permissions:
        - url-pattern: /api/v1/users/assign-roles
          roles:
            - SUPER_ADMIN
            - SYSTEM_MODERATOR
          permissions:

        # ==================== KEYCLOAK CONTROLLER ====================
        - url-pattern: /api/v1/keycloak/**
          roles:
            - SUPER_ADMIN
            - SYSTEM_MODERATOR
          permissions:

        # ==================== ROLE CONTROLLER ====================
        - url-pattern: /api/v1/roles/**
          roles:
            - SUPER_ADMIN
            - SYSTEM_MODERATOR
          permissions:

        # ==================== PERMISSION CONTROLLER ====================
        - url-pattern: /api/v1/permissions/**
          roles:
            - SUPER_ADMIN
            - SYSTEM_MODERATOR
          permissions:

        # ==================== GROUP CONTROLLER ====================
        - url-pattern: /api/v1/groups/**
          roles:
            - SUPER_ADMIN
            - SYSTEM_MODERATOR
          permissions:

        # ==================== MODULE CONTROLLER ====================
        - url-pattern: /api/v1/modules/my-modules
          roles:
            - SUPER_ADMIN
            - SYSTEM_MODERATOR
            - ORG_USER
          permissions:
        - url-pattern: /api/v1/modules/**
          roles:
            - SUPER_ADMIN
            - SYSTEM_MODERATOR
          permissions:

        # ==================== MENU DISPLAY CONTROLLER ====================
        - url-pattern: /api/v1/menu-displays/**
          roles:
            - SUPER_ADMIN
            - SYSTEM_MODERATOR
          permissions:
        
        # ==================== SUBSCRIPTION PLAN CONTROLLER ====================
        - url-pattern: /api/v1/subscription-plans/**
          roles:
            - SUPER_ADMIN
            - SYSTEM_MODERATOR
          permissions:

        # ==================== ORGANIZATION SUBSCRIPTION CONTROLLER ====================
        - url-pattern: /api/v1/subscriptions/subscribe
          roles:
            - SUPER_ADMIN
            - SYSTEM_MODERATOR
            - ORG_OWNER
          permissions:
        - url-pattern: /api/v1/subscriptions/trial
          roles:
            - SUPER_ADMIN
            - SYSTEM_MODERATOR
            - ORG_OWNER
          permissions:
        - url-pattern: /api/v1/subscriptions/upgrade
          roles:
            - SUPER_ADMIN
            - SYSTEM_MODERATOR
            - ORG_OWNER
          permissions:
        - url-pattern: /api/v1/subscriptions/downgrade
          roles:
            - SUPER_ADMIN
            - SYSTEM_MODERATOR
            - ORG_OWNER
          permissions:
        - url-pattern: /api/v1/subscriptions/cancel
          roles:
            - SUPER_ADMIN
            - SYSTEM_MODERATOR
            - ORG_OWNER
          permissions:
        - url-pattern: /api/v1/subscriptions/renew
          roles:
            - SUPER_ADMIN
            - SYSTEM_MODERATOR
            - ORG_OWNER
          permissions:
        - url-pattern: /api/v1/subscriptions/*/extend-trial
          roles:
            - SUPER_ADMIN
            - SYSTEM_MODERATOR
            - ORG_OWNER
          permissions:
        - url-pattern: /api/v1/subscriptions/me/**
          roles:
            - SUPER_ADMIN
            - SYSTEM_MODERATOR
            - ORG_USER
          permissions:
        - url-pattern: /api/v1/subscriptions/**
          roles:
            - SUPER_ADMIN
            - SYSTEM_MODERATOR
          permissions:

        # ==================== MODULE ACCESS CONTROLLER ====================
        - url-pattern: /api/v1/organizations/*/modules/*/access
          roles:
            - SUPER_ADMIN
            - SYSTEM_MODERATOR
            - ORG_USER
          permissions:
        - url-pattern: /api/v1/organizations/*/modules
          roles:
            - SUPER_ADMIN
            - SYSTEM_MODERATOR
            - ORG_USER
          permissions:
        - url-pattern: /api/v1/organizations/*/modules/*/users
          roles:
            - SUPER_ADMIN
            - SYSTEM_MODERATOR
            - ORG_OWNER
            - ORG_ADMIN
          permissions:
        - url-pattern: /api/v1/organizations/*/modules/*/users/bulk
          roles:
            - SUPER_ADMIN
            - SYSTEM_MODERATOR
            - ORG_OWNER
            - ORG_ADMIN
          permissions:
        - url-pattern: /api/v1/organizations/*/users/me/modules
          roles:
            - SUPER_ADMIN
            - SYSTEM_MODERATOR
            - ORG_USER
          permissions:


server:
  port: 8081
  servlet:
    context-path: /account-service
