spring:
  application:
    name: account
  threads:
    virtual:
      enabled: true

  datasource:
    username: serp
    password: serp
    url: jdbc:postgresql://localhost:5432/serp_account
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/serp/protocol/openid-connect/certs
          issuer-uri: http://localhost:8180/realms/serp

app:
  keycloak:
    url: http://localhost:8180
    jwk-set-uri: http://localhost:8180/realms/serp/protocol/openid-connect/certs
    expected-issuer: "http://localhost:8180/realms/serp"
    expected-audience: "account"
    realm: serp
    client-id: serp-account
    client-secret: zZhdvlgJynkXIi9ZEBls4vnpsYokrLza

    admin:
      username: admin
      password: admin
      client-id: admin-cli

  security:
    admin:
      email: quan.tuan.huy@gmail.com
      password: SuperAdmin@123

    jwt:
      private-key: ${JWT_PRIVATE_KEY}
      public-key: ${JWT_PUBLIC_KEY}
      access-token-expiration: 604800000
      refresh-token-expiration: 604800000
      header: Authorization
      prefix: Bearer

    filter:
      publicUrls:
        - first: /api/v1/auth/login
          second: POST
        - first: /api/v1/auth/register
          second: POST
        - first: /api/v1/auth/get-token
          second: POST
        - first: /api/v1/permissions/**
          second: GET
        - first: /api/v1/roles/**
          second: GET
        - first: /api/v1/users/**
          second: GET
      protectedUrls:
        - url-pattern: /api/v1/users/**
          roles:
            - ADMIN
            - SUPER_ADMIN
          permissions:
        - url-pattern: /api/v1/roles/**
          roles:
            - ADMIN
            - SUPER_ADMIN
        - url-pattern: /api/v1/permissions/**
          roles:
            - ADMIN
            - SUPER_ADMIN


server:
  port: 8081
  servlet:
    context-path: /account-service