services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.3
    container_name: serp-keycloak
    command: ["start-dev"]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://serp-postgre-db:5432/serp_keycloak
      KC_DB_USERNAME: serp
      KC_DB_PASSWORD: serp
      KC_HOSTNAME: localhost

      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

    ports:
      - "8180:8080"
    volumes:
      - keycloak_data:/opt/bitnami/keycloak/data
    networks:
      - serp-network

volumes:
  keycloak_data:

networks:
  serp-network:
    external: true
    name: serp_serp-network