app:
  datasource:
    driver: postgres
    host: ${DB_HOST:-localhost}
    port: ${DB_PORT:-5432}
    database: ${DB_NAME:-serp_ptm_task_v2}
    username: ${DB_USERNAME:-serp}
    password: ${DB_PASSWORD:-serp}
    logLevel: info
  redis:
    host: ${REDIS_HOST:-localhost}
    port: ${REDIS_PORT:-6379}
  keycloak:
    url: ${KEYCLOAK_URL}
    realm: serp
    client-id: serp-ptm
    client-secret: ${CLIENT_SECRET}
    jwk-set-uri: ${KEYCLOAK_JWK_SET_URI}
    expected-issuer: ${KEYCLOAK_EXPECTED_ISSUER}
    expected-audience: ${KEYCLOAK_EXPECTED_AUDIENCE}
