app:
  logging:
    level: INFO
  redis:
    host: localhost
    port: 6379

  keycloak:
    url: http://localhost:8180
    realm: serp
    client-id: serp-api-gateway
    client-secret: ${CLIENT_SECRET}
    jwk-set-uri: http://localhost:8180/realms/serp/protocol/openid-connect/certs
    expected-issuer: http://localhost:8180/realms/serp
    expected-audience: 

external:
  services:
    accountService:
      host: localhost
      port: "8081"
      timeout: 15s