app:
  logging:
    level: INFO
  redis:
    host: localhost
    port: 6379

  keycloak:
    url: ${KEYCLOAK_URL}
    realm: serp
    client-id: serp-api-gateway
    client-secret: ${CLIENT_SECRET}
    jwk-set-uri: ${KEYCLOAK_URL}/realms/serp/protocol/openid-connect/certs
    expected-issuer: ${KEYCLOAK_URL}/realms/serp
    expected-audience:

  rateLimit:
    enabled: true
    defaultIP:
      limit: 100
      windowSecs: 60
    defaultUser:
      limit: 200
      windowSecs: 60
    routeOverrides:
      login:
        path: "/api/v1/auth/login"
        method: "POST"
        ip:
          limit: 10
          windowSecs: 60
      register:
        path: "/api/v1/auth/register"
        method: "POST"
        ip:
          limit: 5
          windowSecs: 60
      refreshToken:
        path: "/api/v1/auth/refresh-token"
        method: "POST"
        ip:
          limit: 20
          windowSecs: 60

  cors:
    allowedOrigins:
      - http://localhost:3000
      - https://serp-soict.vercel.app
    allowedMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowedHeaders:
      - Authorization
      - Content-Type
    allowCredentials: true
    maxAge: 3600
    allowFiles: false

external:
  services:
    accountService:
      host: localhost
      port: "8081"
      timeout: 15s
    ptmTask:
      host: localhost
      port: "8083"
      timeout: 15s
    ptmSchedule:
      host: localhost
      port: "8084"
      timeout: 15s
    purchaseService:
      host: localhost
      port: "8088"
      timeout: 15s
    logisticsService:
      host: localhost
      port: "8089"
      timeout: 15s
    crmService:
      host: localhost
      port: "8086"
      timeout: 15s
    notificationService:
      host: localhost
      port: "8090"
      timeout: 15s
    salesService:
      host: localhost
      port: "8090"
      timeout: 15s
    discussService:
      host: localhost
      port: "8092"
      timeout: 15s
