app:
  logging:
    level: warn
  datasource:
    driver: postgres
    host: ${DB_HOST}
    port: ${DB_PORT:-5432}
    database: ${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    logLevel: warn
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT:-6379}
  keycloak:
    url: ${KEYCLOAK_URL}
    realm: serp
    client-id: serp-notification
    client-secret: ${CLIENT_SECRET}
    jwk-set-uri: ${KEYCLOAK_URL}/realms/serp/protocol/openid-connect/certs
    expected-issuer: ${KEYCLOAK_URL}/realms/serp
    expected-audience: 
  kafka:
    producer:
      bootstrapServers:
        - ${KAFKA_BOOTSTRAP_SERVERS}
      requireAcks: 1
      maxMessageBytes: 1048576
      retryMax: 3
      retryBackoffMs: 100
      flushFrequencyMs: 500
      flushMessages: 100
